[workspace]

[package]
name = "aether-init"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[[bin]]
name = "aether-init"
path = "src/main.rs"
test = false
bench = false
doctest = false

[dependencies]
aether-core = { path = "../../core" }

[profile.release]
panic = "abort"
lto = false
opt-level = "s"
codegen-units = 1
